#!/usr/bin/env bash
# ============================================================
# setup_project.sh
# Climate Change & Homelessness in New Jersey — ML Summer 2026
# Run once from the directory where you want the project folder
# Usage: bash setup_project.sh
# ============================================================

PROJECT="climate-homelessness-nj"

echo "Creating project: $PROJECT"

mkdir -p $PROJECT/{data/{raw,interim,processed,external},notebooks/{01_eda,02_features,03_modeling,04_viz},src/{data,features,models,viz},models,reports/{figures,tables},docs,tests}

# ── Placeholder READMEs so git tracks empty dirs ──────────────

cat > $PROJECT/data/raw/README.md << 'EOF'
# Raw Data

**Never modify files in this folder.**

All source data is kept exactly as downloaded. See the table below to reproduce.

| File | Source | URL | Date Pulled | License |
|------|--------|-----|-------------|---------|
| `pit_counts_nj_2007_2024.csv` | HUD Exchange | https://www.hudexchange.info/resource/3031/pit-and-hic-data-since-2007/ | — | Public |
| `nasa_sedac_nj_*.tif` | NASA SEDAC | https://sedac.ciesin.columbia.edu/ | — | See SEDAC terms |
| `noaa_temp_nj_*.nc` | NOAA NCEI | https://www.ncei.noaa.gov/ | — | Public |
| `nj_counties.geojson` | NJ OIT / Census | https://njogis-newjersey.opendata.arcgis.com/ | — | Public |

EOF

cat > $PROJECT/data/interim/README.md << 'EOF'
# Interim Data

Mid-pipeline outputs — partially cleaned or merged, not yet model-ready.
Safe to delete and regenerate from `src/data/`.
EOF

cat > $PROJECT/data/processed/README.md << 'EOF'
# Processed Data

Final cleaned datasets ready for feature engineering and modeling.
Generated by running `src/data/make_dataset.py`.
EOF

cat > $PROJECT/data/external/README.md << 'EOF'
# External Reference Data

Third-party reference files (shapefiles, crosswalks, etc.) not part of
the primary pipeline but used for joins or validation.
EOF

cat > $PROJECT/notebooks/README.md << 'EOF'
# Notebooks

Numbered by phase. Use for exploration only — once logic is stable, 
move it to `src/` as a clean Python module.

| Folder | Purpose |
|--------|---------|
| `01_eda/` | Exploratory data analysis — each data source gets its own notebook |
| `02_features/` | Feature engineering experiments |
| `03_modeling/` | Model training, validation, hyperparameter search |
| `04_viz/` | Final figures for reports |
EOF

cat > $PROJECT/src/__init__.py << 'EOF'
EOF

cat > $PROJECT/src/data/__init__.py << 'EOF'
EOF

cat > $PROJECT/src/data/make_dataset.py << 'EOF'
"""
make_dataset.py
---------------
Entry point for the data pipeline.
Reads raw data, applies cleaning, writes processed outputs.

Usage:
    python -m src.data.make_dataset
"""

import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s — %(message)s")
log = logging.getLogger(__name__)

RAW_DIR = Path("data/raw")
PROCESSED_DIR = Path("data/processed")


def main():
    log.info("Starting data pipeline...")
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    # TODO: call individual loaders for HUD PIT, NOAA, NASA SEDAC
    log.info("Pipeline complete.")


if __name__ == "__main__":
    main()
EOF

cat > $PROJECT/src/features/__init__.py << 'EOF'
EOF

cat > $PROJECT/src/features/build_features.py << 'EOF'
"""
build_features.py
-----------------
Transforms processed data into model-ready feature matrices.
"""

# TODO: county-level feature joins, lag variables, normalization
EOF

cat > $PROJECT/src/models/__init__.py << 'EOF'
EOF

cat > $PROJECT/src/models/train.py << 'EOF'
"""
train.py
--------
Model training script. Reads processed features, fits model,
saves artifact to models/.
"""

# TODO: scikit-learn pipeline, cross-validation, model serialization
EOF

cat > $PROJECT/src/models/evaluate.py << 'EOF'
"""
evaluate.py
-----------
Loads a saved model and runs evaluation metrics.
"""

# TODO: RMSE, R², feature importance, residual plots
EOF

cat > $PROJECT/src/viz/__init__.py << 'EOF'
EOF

cat > $PROJECT/src/viz/plot_helpers.py << 'EOF'
"""
plot_helpers.py
---------------
Shared matplotlib/seaborn utilities for consistent figure styling.
"""

import matplotlib.pyplot as plt

PALETTE = ["#1f4e79", "#2e86c1", "#85c1e9", "#f39c12", "#e74c3c"]

def set_style():
    plt.rcParams.update({
        "figure.dpi": 150,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "font.family": "sans-serif",
    })
EOF

cat > $PROJECT/tests/__init__.py << 'EOF'
EOF

cat > $PROJECT/tests/test_placeholder.py << 'EOF'
"""Placeholder — add unit tests for src/ modules here."""

def test_sanity():
    assert 1 + 1 == 2
EOF

# ── Environment files ──────────────────────────────────────────

cat > $PROJECT/.env.example << 'EOF'
# Copy this file to .env and fill in your values.
# NEVER commit .env to git.

# NASA Earthdata (for SEDAC downloads)
EARTHDATA_USERNAME=your_username_here
EARTHDATA_PASSWORD=your_password_here

# NOAA API (optional — most data is bulk download)
NOAA_API_TOKEN=your_token_here
EOF

cat > $PROJECT/requirements.txt << 'EOF'
# ── Core ──────────────────────────────────────────────────────
numpy>=1.26
pandas>=2.2
scipy>=1.13

# ── Geospatial ────────────────────────────────────────────────
geopandas>=0.14
shapely>=2.0
pyproj>=3.6
rasterio>=1.3        # GeoTIFF / NetCDF raster data
xarray>=2024.1       # NOAA .nc files
netcdf4>=1.6

# ── ML ────────────────────────────────────────────────────────
scikit-learn>=1.4

# ── Visualization ─────────────────────────────────────────────
matplotlib>=3.8
seaborn>=0.13
folium>=0.16         # Interactive NJ county maps

# ── Notebooks ─────────────────────────────────────────────────
jupyter>=1.0
nbstripout>=0.7      # Strip notebook outputs before git commit

# ── Utilities ─────────────────────────────────────────────────
python-dotenv>=1.0   # Load .env files
tqdm>=4.66           # Progress bars for data loops
requests>=2.31       # API calls
EOF

cat > $PROJECT/docs/data_sources.md << 'EOF'
# Data Sources

## HUD Point-in-Time Count
- **URL:** https://www.hudexchange.info/resource/3031/pit-and-hic-data-since-2007/
- **Coverage:** 2007–2024, annual, CoC-level
- **NJ CoCs:** NJ-500 (Atlantic City), NJ-501 (Bergen), NJ-502 (Burlington), NJ-503 (Camden), NJ-504 (Cape May), NJ-505 (Cumberland/Salem/Gloucester), NJ-506 (Essex), NJ-507 (Hudson), NJ-508 (Hunterdon/Somerset/Warren), NJ-509 (Mercer), NJ-510 (Middlesex), NJ-511 (Monmouth), NJ-512 (Morris), NJ-513 (Ocean), NJ-514 (Passaic), NJ-515 (Sussex), NJ-516 (Union)
- **Notes:** Download the Excel workbook; tab structure changes slightly across years

## NASA SEDAC
- **URL:** https://sedac.ciesin.columbia.edu/
- **Datasets of interest:** Climate Hazards Group InfraRed Precipitation (CHIRPS), Gridded Population
- **Access:** Requires free Earthdata account

## NOAA NCEI
- **URL:** https://www.ncei.noaa.gov/
- **Datasets:** Monthly temperature normals, extreme precipitation events, storm data
- **Formats:** CSV (summaries), NetCDF (.nc) for gridded data

## NJ Geospatial
- **County boundaries:** https://njogis-newjersey.opendata.arcgis.com/
- **CoC boundary shapefiles:** HUD EGIS (https://hudgis-hud.opendata.arcgis.com/)
EOF

echo ""
echo "✓ Project scaffold created at ./$PROJECT"
echo ""
echo "Next steps:"
echo "  1. cd $PROJECT"
echo "  2. git init && git add . && git commit -m 'chore: initial scaffold'"
echo "  3. cp .env.example .env   (then fill in credentials)"
echo "  4. mamba env create -f environment.yml && conda activate nasa_sds"
echo "  5. pip install -r requirements.txt"
echo "  6. nbstripout --install   (strips notebook outputs from git)"
echo ""
